twig:
    default_path: '%kernel.project_dir%/templates'
    
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        tmdbBaseUrlPicture: 'https://image.tmdb.org/t/p/original'


when@test:
    twig:
        strict_variables: true
